import { newId } from './id';
import { useEffect, useMemo, useState, useSyncExternalStore, type FormEvent, type ReactNode } from 'react';
import { canRead, difference, duration, emptyLoad, emptyPlan, kindLabels, latest, progress, roleLabels, validatePlan, timestamp, type Action, type Actual, type Command, type Load, type Member, type Plan, type Store, type Trip, type Version } from './domain';
import { AccessError, activeMemberships, cloud, configInvalid, demo, login, Repository } from './repository';
import { demoMembers } from './seed';
import { clearUser, deviceId, read, saveCarry, type Pending } from './offline';
import { download, exportCsv, exportJson, printVersion } from './exports';

import { shellStatus, subscribeShell } from './shell';

type Submit = (action: Action, payload: Record<string, unknown>, revision?: number, tripId?: string) => Promise<boolean>;
const jstNow = () => new Date().toLocaleString('sv-SE', { timeZone: 'Asia/Tokyo' }).replace(' ', 'T').slice(0, 16);
const format = (value?: string) => value ? new Date(/[Z]|[+-]\d\d:\d\d$/.test(value) ? value : `${value}+09:00`).toLocaleString('ja-JP', { timeZone: 'Asia/Tokyo', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '未設定';
function Field({ label, value, onChange, type = 'text', required = false, multiline = false }: { label: string; value: string; onChange: (v: string) => void; type?: string; required?: boolean; multiline?: boolean }) {
  return <label className="field"><span>{label}{required && <b aria-label="必須"> *</b>}</span>{multiline ? <textarea value={value} onChange={e => onChange(e.target.value)} required={required} maxLength={3000} rows={3} /> : <input value={value} onChange={e => onChange(e.target.value)} type={type} required={required} maxLength={type === 'text' ? 1000 : undefined} />}</label>;
}
function Panel({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <section className="panel"><div className="panel-head"><h2>{title}</h2>{action}</div>{children}</section>; }
function Pill({ children, tone = '' }: { children: ReactNode; tone?: string }) { return <span className={`pill ${tone}`}>{children}</span>; }

export default function App() {
  const [actor, setActor] = useState<Member | null>(demo ? demoMembers[0] : null), [memberships, setMemberships] = useState<Member[]>([]);
  const [store, setStore] = useState<Store>({ members: [], trips: [] }), [selected, setSelected] = useState(''), [tab, setTab] = useState('overview');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [online, setOnline] = useState(navigator.onLine), [pending, setPending] = useState<Pending[]>([]), [savedAt, setSavedAt] = useState(''), [savedVersionId, setSavedVersionId] = useState('');
  const [filter, setFilter] = useState(''), [newTrip, setNewTrip] = useState(false), [starting, setStarting] = useState(!demo);
  const repo = useMemo(() => actor ? new Repository(actor) : null, [actor]);
  const trips = store.trips.filter(t => actor && canRead(t, actor));
  const trip = trips.find(t => t.id === selected) ?? trips[0];
  const version = trip && latest(trip);
  async function refresh(target = repo) {
    if (!target) return;
    try { const data = await target.load(); setStore(data); setPending(await target.pending()); } catch (e) { if (e instanceof AccessError) setStore({members:[],trips:[]}); throw e; }
  }
  useEffect(() => {
    if (!cloud) return;
    const load = async () => { try { const rows = await activeMemberships(); setMemberships(rows); setActor(rows[0] ?? null); } catch (e) { setError((e as Error).message); } finally { setStarting(false); } };
    void load();
  }, []);
  useEffect(() => { setStore({ members: [], trips: [] }); setPending([]); setSavedAt(''); setSavedVersionId(''); setSelected(''); if (repo) void refresh(repo).catch(e => setError(e.message)); }, [repo]);
  useEffect(() => {
    const onOnline = () => { setOnline(true); if (repo) void repo.sync().then(() => refresh(repo)).catch(e => setError(e.message)); };
    const onOffline = () => setOnline(false);
    const offlineError = (e: Event) => setError((e as CustomEvent<string>).detail);
    window.addEventListener('online', onOnline); window.addEventListener('offline', onOffline); window.addEventListener('offline-error', offlineError);
    const channel = new BroadcastChannel('operation-instructions'); channel.onmessage = () => { if (repo && demo) void refresh(repo).catch(e => setError(e.message)); };
    return () => { window.removeEventListener('online', onOnline); window.removeEventListener('offline', onOffline); window.removeEventListener('offline-error', offlineError); channel.close(); };
  }, [repo]);
  useEffect(() => { let active = true; setSavedAt(''); if (trip && repo) void read<{ savedAt: string; trip: Trip }>(`${repo.scope}:carry:${trip.id}`).then(v => { if (active) { setSavedAt(v?.savedAt ?? ''); setSavedVersionId(v ? latest(v.trip)?.id ?? '' : ''); } }); return () => { active = false; }; }, [trip?.id, repo]);
  const submit: Submit = async (action, payload, revision, tripId) => {
    if (!repo || busy) return false;
    const cmd: Command = { operationId: newId(), tripId: tripId ?? trip!.id, expectedRevision: revision ?? trip?.revision ?? 0, action, payload };
    setBusy(true); setError(''); setNotice('');
    try {
      if (!navigator.onLine) { await repo.queue(cmd); setPending(await repo.pending()); setNotice('未送信として端末に保存しました。サーバー側の記録は未完了です。'); return true; }
      try { const result = await repo.send(cmd); setSelected(result.id); }
      catch (e) {
        if (e instanceof TypeError || /Failed to fetch|NetworkError|network request/i.test((e as Error).message)) { await repo.queue(cmd); setPending(await repo.pending()); setNotice('送信を確認できません。同じ操作IDで再送する未送信記録を保存しました。'); return true; }
        throw e;
      }
      await refresh(); const channel = new BroadcastChannel('operation-instructions'); channel.postMessage('updated'); channel.close(); setNotice(demo ? 'デモの記録を保存しました。会社の正式保管ではありません。' : 'サーバーで記録を受け付けました。'); return true;
    } catch (e) { setError((e as Error).message); return false; } finally { setBusy(false); }
  };
  async function carry() {
    if (!trip || !repo || !version || busy) return;
    setBusy(true); setError('');
    try { const at = await saveCarry(repo.scope, trip); setSavedAt(at); setSavedVersionId(version.id); setBusy(false); if (actor?.role === 'driver') await submit('deviceSaved', { versionId: version.id, deviceId: deviceId(), savedAt: at }); else setNotice('携行用の写しをこの端末に保存しました。ドライバーの端末保存とは別の記録です。'); }
    catch (e) { setError((e as Error).message); setBusy(false); }
  }
  async function logout() { if (pending.length) { setError('未送信の操作があります。同期するか、保存内容を確認して取り下げてからログアウトしてください。'); return; } if (repo) await repo.signOut(); if (actor) await clearUser(`auth:${actor.id}`); setActor(null); setMemberships([]); setStore({ members: [], trips: [] }); setError(''); }
  if (configInvalid) return <main className="login"><h1>接続設定を確認してください</h1><p>URLと公開用キーの両方が必要です。秘密キー・service_roleは使用できません。設定不備のままデモに切り替えることはありません。</p></main>;
  if (starting) return <main className="login">所属を確認しています…</main>;
  if (!actor) return <Login onLogin={async () => { const rows = await activeMemberships(); setMemberships(rows); setActor(rows[0] ?? null); if (!rows.length) setError('有効な所属がありません。会社のシステム管理者に連絡してください。'); }} error={error} />;
  const manager = actor.role === 'manager', office = manager || actor.role === 'dispatcher', driver = actor.role === 'driver';
  const status = trip && progress(trip);
  const filtered = trips.filter(t => `${t.plan.driverName} ${t.plan.vehicle} ${t.id} ${t.depotId} ${t.plan.startAt} ${t.plan.endAt}`.toLowerCase().includes(filter.toLowerCase()));
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><img src="./icon.svg" alt=""/><div>運行ノート<small>運行指示書管理</small></div></div><p className="sidebar-label">ワークスペース</p><button className={tab !== 'archive' && tab !== 'guide' ? 'nav active' : 'nav'} onClick={() => setTab('overview')}>▤ <span>運行と指示書</span></button><button className={tab === 'archive' ? 'nav active' : 'nav'} onClick={() => setTab('archive')}>▦ <span>検索・保管帳票</span></button><button className={tab === 'guide' ? 'nav active' : 'nav'} onClick={() => setTab('guide')}>？ <span>利用ガイド</span></button><div className="sidebar-bottom"><span className="avatar">{actor.name.slice(0, 1)}</span><div>{actor.name}<small>{roleLabels[actor.role]}</small></div></div></aside>
    <div className="workspace"><header className="topbar"><span>{demo ? 'サンプル営業所' : `営業所 ${actor.depotId.slice(0, 8)}`} <span className="muted">/ {roleLabels[actor.role]}</span></span><div className="top-actions"><Pill tone={online ? 'green' : 'amber'}>{online ? 'オンライン' : 'オフライン'}</Pill>{demo ? <label className="role-picker">デモ役割<select aria-label="デモ役割" value={actor.id} onChange={e => { setActor(demoMembers.find(m => m.id === e.target.value)!); setError(''); }} disabled={busy}>{demoMembers.map(m => <option key={m.id} value={m.id}>{roleLabels[m.role]}</option>)}</select></label> : <><select aria-label="営業所・役割" value={`${actor.depotId}:${actor.role}`} onChange={e => setActor(memberships.find(m => `${m.depotId}:${m.role}` === e.target.value)!)}>{memberships.map(m => <option key={`${m.depotId}:${m.role}`} value={`${m.depotId}:${m.role}`}>{m.depotId.slice(0, 8)} / {roleLabels[m.role]}</option>)}</select><button className="text-button" onClick={() => void logout()}>ログアウト</button></>}</div></header>
      <main><div className="demo-banner">{demo ? 'デモ・正式指示ではない｜架空データで操作を確認できます。実際の運行情報は入力しないでください。' : '点呼は別途実施してください。予定の入力だけで改善基準の遵守を判定しません。'}</div>
      {!online && <p className="callout">端末で最後に取得した版を表示しています。サーバーの最新版は未確認です。変更運行は進めず、安全な場所で会社へ連絡してください。</p>}{error && <div className="message error" role="alert">{error}<button onClick={() => setError('')} aria-label="エラーを閉じる">×</button></div>}{notice && <div className="message success" role="status">{notice}</div>}
      <div className="page-heading"><div><p className="eyebrow">OPERATION CONTROL</p><h1>{tab === 'archive' ? '検索・保管帳票' : tab === 'guide' ? '利用ガイド' : '運行と指示書'}</h1><p className="muted">計画の変更から双方の記録まで、一つの運行にまとめて。</p></div><div className="button-row"><button onClick={() => void refresh().catch(e => setError(e.message))} disabled={busy}>↻ 再読込</button>{office && <button className="primary" onClick={() => setNewTrip(true)} disabled={!online || busy}>＋ 運行を作成</button>}</div></div>
      {pending.length > 0 && <Panel title={`未送信の操作 ${pending.length}件`} action={<button disabled={!online || busy} onClick={() => { setBusy(true); void repo!.sync().then(() => refresh()).catch(e => setError(e.message)).finally(() => setBusy(false)); }}>同期する</button>}><p>確認・申請は送信成功まで完了しません。競合した操作は内容と対象版を確認してから再送してください。</p>{pending.map(p => <div key={p.command.operationId} className="queue-item"><Pill tone="amber">{p.status === 'conflict' ? '要再確認' : '未送信'}</Pill><span>{p.command.action} / {format(p.queuedAt)}<small>{p.message}</small></span><details><summary>保存した内容</summary><pre>{JSON.stringify(p.command.payload, null, 2)}</pre></details><button onClick={() => download(`未送信-${p.command.operationId}.json`, JSON.stringify(p, null, 2), 'application/json')}>内容をJSON保存</button><button disabled={busy} onClick={() => { void repo!.cancel(p.command.operationId).then(async () => setPending(await repo!.pending())).catch(e => setError(e.message)); }}>取り下げて端末に記録</button>{p.status === 'conflict' && <button disabled={!online || busy} onClick={() => { const target = trips.find(t => t.id === p.command.tripId); if (target) void repo!.retry(p.command.operationId, target.revision).then(() => refresh()).catch(e => setError(e.message)); }}>内容を確認して再送</button>}</div>)}</Panel>}
      {newTrip && <Panel title="新しい運行"><CreateTrip members={store.members.filter(m => m.role === 'driver' && m.depotId === actor.depotId)} actor={actor} busy={busy} submit={submit} close={() => setNewTrip(false)} /></Panel>}
      {tab === 'guide' ? <Guide /> : tab === 'archive' ? <Panel title={`${filtered.length}件の運行`} action={<div className="button-row"><button onClick={() => exportCsv(filtered)}>CSV</button><button onClick={() => exportJson(filtered)}>履歴一式 JSON</button></div>}><input aria-label="帳票検索" placeholder="日付・営業所ID・氏名・車両・運行IDで検索" value={filter} onChange={e => setFilter(e.target.value)} /><div className="trip-list">{filtered.map(t => <button key={t.id} onClick={() => { setSelected(t.id); setTab('overview'); }}><strong>{t.plan.driverName}</strong><span>{t.plan.vehicle} / {format(t.plan.startAt)} → {format(t.plan.endAt)}</span><Pill>{t.status === 'closed' ? '保存確定' : t.status === 'draft' ? '作成中' : '指示記録中'}</Pill></button>)}</div></Panel> : !trip ? <Panel title="運行がありません"><p>所属する営業所の運行が表示されます。運行管理者・配車担当は「運行を作成」から登録できます。</p></Panel> : <>
      <div className="trip-selector"><label>表示する運行<select value={trip.id} onChange={e => { setSelected(e.target.value); setTab('overview'); }}>{trips.map(t => <option key={t.id} value={t.id}>{t.plan.driverName} / {t.plan.vehicle} / {format(t.plan.startAt)}</option>)}</select></label><span className="muted">ID {trip.id.slice(0, 8)}</span></div>
      <section className="trip-hero"><div><div className="button-row"><Pill tone={trip.status === 'closed' ? 'green' : 'amber'}>{trip.status === 'closed' ? '保存確定' : version ? status!.complete ? '双方記録・保存通知あり' : '指示記録を確認' : '作成中・未発行'}</Pill><span className="hero-id">第{version?.number ?? '—'}版</span></div><h2>{(version?.snapshot ?? trip.plan).startPlace || '出庫地点未入力'} <span>→</span> {(version?.snapshot ?? trip.plan).endPlace || '帰庫地点未入力'}</h2><p>{trip.plan.driverName} <span>・</span> {trip.plan.vehicle || '車両未設定'}</p><div className="hero-dates"><div><small>出庫予定</small><strong>{format((version?.snapshot ?? trip.plan).startAt)}</strong></div><div><small>帰庫予定 {(version?.snapshot ?? trip.plan).returnProvisional ? '（暫定）' : ''}</small><strong>{format((version?.snapshot ?? trip.plan).endAt)}</strong></div></div></div><div className="hero-controls"><button onClick={() => { try { printVersion(trip, version!.id, demo); } catch (e) { setError((e as Error).message); } }} disabled={!version}>指示書 / PDF印刷 ↗</button><button className="light" disabled={!version || busy} onClick={() => void carry()}>↓ この端末に保存</button><small>{savedAt ? `端末保存 ${format(savedAt)}（${savedVersionId === version?.id ? '最新取得版' : '旧版・再保存が必要'}）` : 'この端末の携行版は未保存'}</small></div></section>
      <div className="status-grid">{[['company', '会社写し', '発行内容を固定保存'], ['voice', '直接対話', '実際の通話を記録'], ['driver', 'ドライバー記録', 'この版の変更を確認'], ['device', '端末保存通知', '本人の保存を受信']].map(([key, label, desc], i) => <div className="status-card" key={key}><span className={`step-dot ${status![key as keyof typeof status] ? 'done' : ''}`}>{status![key as keyof typeof status] ? '✓' : i + 1}</span><div><strong>{label}</strong><small>{desc}</small></div><Pill tone={status![key as keyof typeof status] ? 'green' : 'amber'}>{status![key as keyof typeof status] ? '記録済み' : '未記録'}</Pill></div>)}</div>
      <nav className="tabs" aria-label="運行詳細">{[['overview', '運行計画'], ['loads', `荷物・変更申請 ${trip.requests.filter(r => r.status === 'submitted').length || ''}`], ['records', '指示と本人記録'], ['history', '版履歴・実績']].map(([key, label]) => <button key={key} aria-current={tab === key ? 'page' : undefined} className={tab === key ? 'selected' : ''} onClick={() => setTab(key)}>{label}</button>)}</nav>
      {tab === 'overview' && <div className="detail-grid"><div><Panel title="発行済みの運行計画" action={<Pill>予定 / JST</Pill>}>{version ? <PlanView plan={version.snapshot} /> : <p>初版を発行すると、全項目の固定版が表示されます。</p>}</Panel>{office && trip.status !== 'closed' && <Panel title="次の版の下書き"><PlanEditor key={trip.id} trip={trip} submit={submit} busy={busy || !online} /></Panel>}</div><aside className="detail-aside"><Panel title="一の運行の期間"><strong className="duration">{Number.isFinite(duration(version?.snapshot ?? trip.plan)) ? duration(version?.snapshot ?? trip.plan).toFixed(1) : '—'}<small>時間</small></strong><p className="muted">最初の勤務開始から最後の勤務終了まで。144時間以内でも他の勤務基準の適合は判定できません。</p><p>フェリー特例はこの版では適用しません。</p></Panel><Panel title="次便が未確定の場合"><p>{(version?.snapshot ?? trip.plan).fallback || '未入力'}</p><div className="callout"><small>次回の会社への連絡</small><strong>{format((version?.snapshot ?? trip.plan).nextContact)}</strong></div>{(version?.snapshot ?? trip.plan).officePhone && <a className="phone-button" href={`tel:${(version?.snapshot ?? trip.plan).officePhone.replace(/[^+\d]/g, '')}`}>会社に電話する</a>}</Panel><Panel title="計画を変更するとき"><p>荷物情報を申請 → 会社が安全計画を確認 → 修正版発行 → 直接対話 → 本人記録・端末保存。</p><small>文字の既読だけで変更指示完了にしません。入力は安全に停車して行ってください。</small></Panel></aside></div>}
      {tab === 'loads' && <><Panel title="荷物・変更申請"><p className="muted">新しい荷物は申請として保存します。正式な指示には運行管理者の発行が必要です。</p>{(driver || actor.role === 'dispatcher') && trip.status !== 'closed' && <LoadForm key={trip.id} trip={trip} busy={busy} submit={submit} />}{trip.requests.length ? trip.requests.slice().reverse().map(r => <article className="request" key={r.id}><div className="panel-head"><h3>{r.load.name}</h3><Pill tone={r.status === 'issued' ? 'green' : 'amber'}>{{ submitted: '申請済み', returned: '差戻し', rejected: '却下', issued: '修正版発行済み' }[r.status]}</Pill></div><p>{r.load.pickup} {format(r.load.pickupAt)} → {r.load.delivery} {format(r.load.deliveryAt)}</p><small>{r.author} / 基準 第{r.baseVersion}版 / {format(r.submittedAt)}</small><p>理由：{r.reason}</p><p>連絡元：{r.load.source} / 荷役：{r.load.handling || '未入力'} / 重量：{r.load.weight || '未入力'} / 個数：{r.load.quantity || '未入力'}</p>{r.response && <p className="callout">会社回答：{r.response}</p>}{manager && r.status === 'submitted' && trip.status !== 'closed' && <button disabled={busy || !online || r.baseVersion !== (version?.number ?? 0)} onClick={() => void submit('savePlan', { plan: { ...trip.plan, stops: [...trip.plan.stops.filter(s => !s.id.startsWith(r.id)), { id: r.id + '-pickup', kind: 'pickup', place: r.load.pickup, arrive: r.load.pickupAt, depart: r.load.pickupAt, notes: r.load.name + ' / 荷役時間を設定してください' }, { id: r.id + '-delivery', kind: 'delivery', place: r.load.delivery, arrive: r.load.deliveryAt, depart: r.load.deliveryAt, notes: r.load.name + ' / 荷役時間を設定してください' }].sort((a, b) => timestamp(a.arrive) - timestamp(b.arrive)) }, baseVersion: version?.number ?? 0 })}>申請の積卸を下書きに反映</button>}{manager && r.status === 'submitted' && trip.status !== 'closed' && <RequestDecision id={r.id} submit={submit} busy={busy || !online} />}</article>) : <p className="empty">変更申請はありません。</p>}</Panel>{manager && trip.status !== 'closed' && <Panel title="修正版発行"><Publish key={trip.revision} trip={trip} submit={submit} busy={busy || !online} /></Panel>}</>}
      {tab === 'records' && <><div className="detail-grid"><Panel title="直接対話の指示記録">{version && manager && trip.status !== 'closed' && <VoiceForm key={version.id} version={version} trip={trip} submit={submit} busy={busy || !online} />}{trip.voices.filter(v => v.versionId === version?.id).map(v => <div key={v.id} className="record"><strong>{v.manager} → {v.recipient}</strong><small>実日時 {format(v.actualAt)} / 受信 {format(v.receivedAt)} / {v.method === 'phone' ? '電話' : '音声通話'}</small><p>{v.notes}</p></div>)}{!status!.voice && <p className="empty">最新の版の直接対話は未記録です。</p>}</Panel><Panel title="ドライバーの変更記録">{version && driver && !status!.driver && trip.status !== 'closed' && <AckForm key={version.id} version={version} submit={submit} busy={busy} />}{trip.driverRecords.filter(r => r.versionId === version?.id).map(r => <div key={r.id} className="record"><strong>{r.driver}</strong><small>実日時 {format(r.actualAt)} / 受信 {format(r.receivedAt)}</small><p>{r.notes}</p></div>)}{!status!.driver && <p className="muted">本人がこの版の内容を記録する必要があります。旧版の記録は流用しません。</p>}</Panel></div>{manager && trip.status !== 'closed' && <Panel title="運行終了と保管"><CloseTrip key={trip.revision} trip={trip} submit={submit} busy={busy || !online} /></Panel>}</>}
      {tab === 'history' && <><Panel title="発行済みの全版" action={<button onClick={() => exportJson([trip])}>履歴一式を保存</button>}>{trip.versions.slice().reverse().map((v, reverseIndex) => { const originalIndex = trip.versions.length - reverseIndex - 1; return <details className="version" key={v.id} open={v.id === version?.id}><summary>第{v.number}版　{format(v.issuedAt)}　{v.issuer} <Pill>{v.reason}</Pill></summary><div className="button-row"><button onClick={() => { try { printVersion(trip, v.id, demo); } catch (e) { setError((e as Error).message); } }}>この版をPDF印刷</button><small>SHA-256 {v.hash}</small></div><Diff before={trip.versions[originalIndex - 1]?.snapshot} after={v.snapshot} /><div className="muted">会社写し保存 {format(v.companyCopy.savedAt)} / 通話 {trip.voices.filter(x => x.versionId === v.id).length}件 / 本人記録 {trip.driverRecords.filter(x => x.versionId === v.id).length}件</div></details>; })}</Panel><Panel title="実績（予定とは別記）">{driver && trip.status !== 'closed' && <ActualForm key={trip.id} busy={busy} submit={submit} />}{trip.actuals.map(a => <div key={a.id} className="record"><strong>{kindLabels[a.kind]} / {a.place}</strong><small>{format(a.startAt)} → {format(a.endAt)} / {a.actor}</small><p>{a.notes}</p></div>)}{!trip.actuals.length && <p className="empty">実績はまだ登録されていません。</p>}</Panel><Panel title="操作履歴">{trip.audit.slice().reverse().map(a => <div key={a.id} className="audit-row"><span>{a.action}</span><span>{a.actor}</span><small>{format(a.at)}</small></div>)}</Panel></>}
      </>}
      <footer>運行ノート v0.1 <span>｜</span> 法令根拠：<a href="https://www.mlit.go.jp/jidosha/anzen/03safety/resourse/data/construction_kamotsu.pdf" target="_blank" rel="noreferrer">国交省 解釈通達（2026.6.26）</a> <span>｜</span> データは公開リポジトリに保存しません。</footer></main>
    </div></div>;
}

function Login({ onLogin, error }: { onLogin: () => Promise<void>; error: string }) {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  return <main className="login"><img src="./icon.svg" alt="" width="64"/><h1>運行ノート</h1><p>会社から招待された個別アカウントでログインしてください。</p><form onSubmit={async e => { e.preventDefault(); setBusy(true); setMessage(''); try { await login(email, password); setPassword(''); await onLogin(); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); } }}><Field label="メールアドレス" value={email} onChange={setEmail} type="email" required/><Field label="パスワード" value={password} onChange={setPassword} type="password" required/><button className="primary" disabled={busy}>ログイン</button></form>{(message || error) && <p role="alert">{message || error}</p>}</main>;
}
function CreateTrip({ members, actor, busy, submit, close }: { members: Member[]; actor: Member; busy: boolean; submit: Submit; close: () => void }) {
  const [driver, setDriver] = useState(members[0]?.id ?? ''), [vehicle, setVehicle] = useState('');
  return <form className="form-grid" onSubmit={async e => { e.preventDefault(); if (await submit('create', { depotId: actor.depotId, driverId: driver, plan: { ...emptyPlan(), vehicle } }, 0, newId())) close(); }}><label className="field"><span>担当ドライバー</span><select value={driver} onChange={e => setDriver(e.target.value)} required><option value="">選択してください</option>{members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><Field label="車両番号" value={vehicle} onChange={setVehicle} required/><div className="button-row"><button className="primary" disabled={busy || !driver}>下書きを作成</button><button type="button" onClick={close}>閉じる</button></div></form>;
}
function PlanView({ plan }: { plan: Plan }) {
  return <><dl className="facts"><dt>経路</dt><dd>{plan.route}</dd><dt>注意箇所</dt><dd>{plan.cautions}</dd><dt>交替地点・要員</dt><dd>{plan.exchange} {plan.crew}</dd><dt>安全事項</dt><dd>{plan.safety}</dd><dt>最初・最後の勤務</dt><dd>{format(plan.dutyStart)} → {format(plan.dutyEnd)}（予定）</dd></dl><div className="timeline">{plan.stops.map(s => <div className={`timeline-item kind-${s.kind}`} key={s.id}><span className="timeline-dot"/><div className="timeline-time">{format(s.arrive)}<small>→ {format(s.depart)}</small></div><div><Pill tone={s.kind === 'rest' ? 'green' : ''}>{kindLabels[s.kind]}</Pill><h3>{s.place}</h3><p>{s.notes}</p></div></div>)}</div></>;
}
function PlanEditor({ trip, submit, busy }: { trip: Trip; submit: Submit; busy: boolean }) {
  const [plan, setPlan] = useState<Plan>(() => structuredClone(trip.plan)), [source, setSource] = useState({ revision: trip.revision, base: latest(trip)?.number ?? 0 }), [message, setMessage] = useState('');
  const set = (key: keyof Plan, value: unknown) => setPlan(p => ({ ...p, [key]: value }));
  async function save(e: FormEvent) { e.preventDefault(); setMessage(''); if (await submit('savePlan', { plan, baseVersion: source.base }, source.revision)) { setMessage('下書き保存後の内容は「最新版を読み込む」で確認できます。'); } }
  const fields: [keyof Plan, string, string?][] = [['vehicle', '車両番号'], ['crew', '交替要員（任意）'], ['startPlace', '出庫地点'], ['startAt', '出庫日時', 'datetime-local'], ['endPlace', '帰庫地点'], ['endAt', '帰庫日時', 'datetime-local'], ['dutyStart', '最初の勤務開始', 'datetime-local'], ['dutyEnd', '最後の勤務終了', 'datetime-local'], ['nextContact', '次回の会社連絡', 'datetime-local'], ['officePhone', '会社の電話番号', 'tel']];
  return <form onSubmit={save}><p className="muted">下書きの保存で発行済み版は変わりません。日時はすべて日本時間です。</p><div className="button-row"><Pill>審査基準 第{source.base}版</Pill><button type="button" onClick={() => { setPlan(structuredClone(trip.plan)); setSource({ revision: trip.revision, base: latest(trip)?.number ?? 0 }); setMessage(''); }}>最新版を読み込む</button></div>{source.revision !== trip.revision && <p className="callout">運行が更新されました。入力中の内容を確認し、最新版を読み込んでから編集してください。</p>}<div className="form-grid">{fields.map(([key, label, type]) => <Field key={key} label={label} type={type} value={String(plan[key])} onChange={v => set(key, v)} />)}</div><label className="checkbox"><input type="checkbox" checked={plan.returnProvisional} onChange={e => set('returnProvisional', e.target.checked)} />帰庫予定は暫定（実績ではない）</label>{([['route', '経路・主な道路'], ['cautions', '注意箇所（該当なしの場合も明記）'], ['exchange', '運転・業務交替地点（なしの場合も明記）'], ['safety', '安全事項・休息計画'], ['fallback', '次便未確定時の行動']] as const).map(([key, label]) => <Field key={key} label={label} value={plan[key]} onChange={v => set(key, v)} multiline />)}<h3>行程・休憩・休息</h3>{plan.stops.map((s, index) => <div className="stop-editor" key={s.id}><div className="form-grid"><label className="field"><span>種別</span><select value={s.kind} onChange={e => set('stops', plan.stops.map(x => x.id === s.id ? { ...x, kind: e.target.value } : x))}>{Object.entries(kindLabels).filter(([k]) => !['drive', 'dutyStart', 'dutyEnd'].includes(k)).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><Field label="地点・住所" value={s.place} onChange={v => set('stops', plan.stops.map(x => x.id === s.id ? { ...x, place: v } : x))}/><Field label="到着・開始" type="datetime-local" value={s.arrive} onChange={v => set('stops', plan.stops.map(x => x.id === s.id ? { ...x, arrive: v } : x))}/><Field label="出発・終了" type="datetime-local" value={s.depart} onChange={v => set('stops', plan.stops.map(x => x.id === s.id ? { ...x, depart: v } : x))}/></div><Field label="備考" value={s.notes} onChange={v => set('stops', plan.stops.map(x => x.id === s.id ? { ...x, notes: v } : x))}/><div className="button-row"><button type="button" disabled={index === 0} onClick={() => { const stops = [...plan.stops]; [stops[index - 1], stops[index]] = [stops[index], stops[index - 1]]; set('stops', stops); }}>↑ 上へ</button><button type="button" onClick={() => set('stops', plan.stops.filter(x => x.id !== s.id))}>行程を外す</button></div></div>)}<div className="button-row"><button type="button" onClick={() => set('stops', [...plan.stops, { id: newId(), kind: 'via', place: '', arrive: '', depart: '', notes: '' }])}>＋ 行程を追加</button><button className="primary" disabled={busy || source.revision !== trip.revision}>下書きを保存</button></div>{message && <p role="status">{message}</p>}<details className="validation"><summary>発行前の入力チェック（{validatePlan(plan).length}件）</summary>{validatePlan(plan).map(x => <p key={x}>{x}</p>)}</details></form>;
}
function Diff({ before, after }: { before?: Plan; after: Plan }) { return <div className="diff-table">{difference(before, after).map(d => <div className="diff-row" key={d.label}><strong>{d.label}</strong><div><small>旧版</small><p>{d.before}</p></div><div><small>新版</small><p>{d.after}</p></div></div>)}</div>; }
function Publish({ trip, submit, busy }: { trip: Trip; submit: Submit; busy: boolean }) {
  const [reviewed, setReviewed] = useState(false), [reason, setReason] = useState(''), [requestIds, setRequestIds] = useState<string[]>([]);
  const errors = validatePlan(trip.plan), current = latest(trip);
  return <form onSubmit={async e => { e.preventDefault(); await submit('publish', { baseVersion: current?.number ?? 0, draftRevision: trip.draftRevision, reason, safetyReviewed: reviewed, requestIds }); }}><p>申請を選んでも積卸先は自動で計画に入れません。運行計画の下書きへ反映して、安全を確認してから発行してください。</p><Diff before={current?.snapshot} after={trip.plan}/>{trip.requests.filter(r => r.status === 'submitted').map(r => <label className="checkbox" key={r.id}><input type="checkbox" checked={requestIds.includes(r.id)} disabled={r.baseVersion !== (current?.number ?? 0)} onChange={e => setRequestIds(e.target.checked ? [...requestIds, r.id] : requestIds.filter(id => id !== r.id))} />{r.load.name}を今回の版で処理済みにする（基準 第{r.baseVersion}版）</label>)}{errors.length > 0 && <div className="callout">{errors.map(x => <p key={x}>{x}</p>)}</div>}<Field label="発行・変更理由" value={reason} onChange={setReason} required multiline/><label className="checkbox"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} required />差分・荷物・勤務実績・休憩・休息を確認し、安全な計画と判断しました。</label><button className="primary" disabled={busy || !reviewed || errors.length > 0}>第{(current?.number ?? 0) + 1}版を発行</button></form>;
}
function LoadForm({ trip, busy, submit }: { trip: Trip; busy: boolean; submit: Submit }) {
  const [load, setLoad] = useState<Load>(emptyLoad), [reason, setReason] = useState(''), [baseVersion, setBaseVersion] = useState(latest(trip)?.number ?? 0);
  const fields: [keyof Load, string, string?][] = [['name', '荷物名'], ['weight', '重量'], ['quantity', '個数'], ['source', '配車連絡元・利用運送会社'], ['receivedAt', '連絡を受けた日時', 'datetime-local'], ['pickup', '積地の住所'], ['pickupAt', '積日時', 'datetime-local'], ['delivery', '卸地の住所'], ['deliveryAt', '卸日時', 'datetime-local'], ['handling', '荷役方法・附帯作業'], ['contact', '荷物の連絡先']];
  return <form className="load-form" onSubmit={async e => { e.preventDefault(); if (await submit('submitRequest', { load, reason, baseVersion })) { setLoad(emptyLoad()); setReason(''); setBaseVersion(latest(trip)?.number ?? 0); } }}><p className="safety-note">入力は安全に停車して行ってください。申請の基準：第{baseVersion}版</p>{baseVersion !== (latest(trip)?.number ?? 0) && <p className="callout">新しい版が発行されました。最新指示を確認してから基準を変更してください。<button type="button" onClick={() => setBaseVersion(latest(trip)?.number ?? 0)}>最新指示を確認して基準を変更</button></p>}<div className="form-grid">{fields.map(([key, label, type]) => <Field key={key} label={label} type={type} value={load[key]} onChange={v => setLoad(p => ({ ...p, [key]: v }))} required={['name', 'source', 'receivedAt', 'pickup', 'pickupAt', 'delivery', 'deliveryAt'].includes(key)}/>)}</div><Field label="変更理由・会社への連絡事項" value={reason} onChange={setReason} required multiline/><button className="primary" disabled={busy || baseVersion !== (latest(trip)?.number ?? 0)}>{navigator.onLine ? '会社へ申請する' : '未送信として保存'}</button></form>;
}
function RequestDecision({ id, submit, busy }: { id: string; submit: Submit; busy: boolean }) { const [response, setResponse] = useState(''); return <div><Field label="差戻し・却下理由" value={response} onChange={setResponse}/><div className="button-row"><button disabled={busy || !response.trim()} onClick={() => void submit('decideRequest', { requestId: id, status: 'returned', response })}>差戻し</button><button disabled={busy || !response.trim()} onClick={() => void submit('decideRequest', { requestId: id, status: 'rejected', response })}>却下</button></div></div>; }
function VoiceForm({ version, trip, submit, busy }: { version: Version; trip: Trip; submit: Submit; busy: boolean }) { const [at, setAt] = useState(jstNow), [notes, setNotes] = useState(''), [recipient, setRecipient] = useState(trip.plan.driverName), [method, setMethod] = useState('phone'); return <form key={version.id} onSubmit={async e => { e.preventDefault(); if (await submit('voice', { versionId: version.id, actualAt: at, notes, recipient, method })) setNotes(''); }}><p>第{version.number}版について実際に直接対話した内容を記録します。</p><Field label="実際に指示した日時（JST）" type="datetime-local" value={at} onChange={setAt} required/><Field label="相手" value={recipient} onChange={setRecipient} required/><label className="field"><span>方法</span><select value={method} onChange={e => setMethod(e.target.value)}><option value="phone">電話</option><option value="voice">直接対話できる音声通話</option></select></label><Field label="変更内容・指示の要点" value={notes} onChange={setNotes} required multiline/><button className="primary" disabled={busy}>通話の実記録を保存</button></form>; }
function AckForm({ version, submit, busy }: { version: Version; submit: Submit; busy: boolean }) { const [at, setAt] = useState(jstNow), [notes, setNotes] = useState(''); return <form onSubmit={async e => { e.preventDefault(); await submit('ack', { versionId: version.id, actualAt: at, notes }); }}><p className="safety-note">安全に停車して、指示書の第{version.number}版と通話内容を確認してください。</p><PlanView plan={version.snapshot}/><Field label="実際に確認・記録した日時（JST）" type="datetime-local" value={at} onChange={setAt} required/><Field label="確認して記録する変更内容" value={notes} onChange={setNotes} required multiline/><button className="primary" disabled={busy}>この変更内容を運行指示書に記録する</button></form>; }
function ActualForm({ submit, busy }: { submit: Submit; busy: boolean }) { const [kind, setKind] = useState<Actual['kind']>('pickup'), [place, setPlace] = useState(''), [start, setStart] = useState(jstNow), [end, setEnd] = useState(jstNow), [notes, setNotes] = useState(''); return <form onSubmit={async e => { e.preventDefault(); if (await submit('actual', { kind, place, startAt: start, endAt: end, notes })) { setPlace(''); setNotes(''); } }}><p className="safety-note">安全に停車して、実際に行った業務を入力してください。</p><div className="form-grid"><label className="field"><span>実績種別</span><select value={kind} onChange={e => setKind(e.target.value as Actual['kind'])}>{Object.entries(kindLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><Field label="地点" value={place} onChange={setPlace} required/><Field label="実際の開始（JST）" type="datetime-local" value={start} onChange={setStart} required/><Field label="実際の終了（JST）" type="datetime-local" value={end} onChange={setEnd} required/></div><Field label="補足・遅延理由" value={notes} onChange={setNotes} multiline/><button disabled={busy}>実績を保存</button></form>; }
function CloseTrip({ trip, submit, busy }: { trip: Trip; submit: Submit; busy: boolean }) { const [reviewed, setReviewed] = useState(false); return <form onSubmit={async e => { e.preventDefault(); await submit('close', { actualsReviewed: reviewed }); }}><p>勤務開始・勤務終了の実績と未処理申請を確認します。保存確定後は編集できません。</p><label className="checkbox"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} required />最終実績と変更履歴を確認しました。</label><button disabled={busy || !reviewed || !progress(trip).complete} className="primary">運行終了・保存確定</button></form>; }
function Guide() { const shell = useSyncExternalStore(subscribeShell, shellStatus); return <Panel title="運行と変更の記録"><ol className="guide"><li><strong>会社で初版を作る</strong><p>運行作成 → 計画の下書き保存 → 「荷物・変更申請」の発行欄で必須項目と勤務計画を確認 → 第1版発行。</p></li><li><strong>次の荷物を申請する</strong><p>ドライバーは停車して積卸先や配車連絡を申請。未確定の荷物は架空の時刻を作って確定しません。差戻し後は修正した新しい申請を送ります。</p></li><li><strong>変更を指示する</strong><p>会社は下書きに経路・積卸・休憩・休息を反映し、差分を確認して修正版発行。直接対話できる電話・音声通話で指示し、実日時を記録します。</p></li><li><strong>本人が記録し端末に保存する</strong><p>本人のアカウントで最新の版を確認し、変更内容を記録。「この端末に保存」でIndexedDBへの保存成功後に通知します。未送信は完了表示に使いません。</p></li><li><strong>実績と全版を保管する</strong><p>勤務開始・終了を含む実績を入力して会社が保存確定。初版・修正版・双方記録は履歴一式JSON、一覧はCSV、各版はブラウザの印刷からPDFとして保存できます。</p></li></ol><h3>通信できない場合</h3><p className="callout">{shell}</p><p>保存済みの画面・指示書を閲覧し、通常の変更運行は進めず安全な場所で会社と直接対話してください。未送信操作は再接続後に同期。競合時は対象版と保存内容を確認します。</p><h3>この実装の範囲</h3><p>添付画像・自動OCR、フェリー控除、勤務履歴との総合的な改善基準判定、管理者による利用者招待画面、PDFファイルのサーバー固定保管は未実装です。DBの定期バックアップ・別保存先・復元体制と具体的な電子携行方式は本番導入前に設定・確認します。</p><h3>デモの確認方法</h3><p>右上の「デモ役割」を切り替えて、運行管理者・ドライバーそれぞれの操作を試せます。デモの役割切替は本番の認証機能ではありません。</p></Panel>; }
