import { csvCell, kindLabels, type Trip } from './domain';
export function download(name: string, content: string, type: string) {
  const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export function exportJson(trips: Trip[]) { download(`運行記録-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify({ schemaVersion: 1, exportedAt: new Date().toISOString(), trips }, null, 2), 'application/json'); }
export function exportCsv(trips: Trip[]) {
  const headers = ['運行ID', '運転者', '車両', '状態', '版', '発行者', '発行日時', '出庫予定', '帰庫予定', '勤務開始予定', '勤務終了予定', '暫定帰庫', '変更理由', '版ハッシュ'];
  const rows = trips.flatMap(t => t.versions.map(v => [t.id, v.snapshot.driverName, v.snapshot.vehicle, t.status, String(v.number), v.issuer, v.issuedAt, v.snapshot.startAt, v.snapshot.endAt, v.snapshot.dutyStart, v.snapshot.dutyEnd, v.snapshot.returnProvisional ? '暫定' : '確定', v.reason, v.hash]));
  download('運行一覧.csv', '\ufeff' + [headers, ...rows].map(row => row.map(csvCell).join(',')).join('\r\n'), 'text/csv;charset=utf-8');
}
export function printVersion(trip: Trip, versionId: string, demo: boolean) {
  const v = trip.versions.find(v => v.id === versionId); if (!v) throw new Error('版が見つかりません。');
  const escape = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
  const rows = (items: [string, unknown][]) => items.map(([a, b]) => `<tr><th>${escape(a)}</th><td>${escape(b).replaceAll('\n', '<br>')}</td></tr>`).join('');
  const p = v.snapshot;
  const voices = trip.voices.filter(r => r.versionId === v.id), drivers = trip.driverRecords.filter(r => r.versionId === v.id), receipts = trip.receipts.filter(r => r.versionId === v.id);
  const win = window.open('', '_blank'); if (!win) throw new Error('印刷画面のポップアップを許可してください。');
  win.document.write(`<!doctype html><html lang="ja"><meta charset="utf-8"><title>運行指示書-${escape(trip.id)}-v${v.number}</title><style>body{font:12px sans-serif;color:#111;margin:24px}h1{font-size:22px}h2{font-size:16px;margin-top:24px}table{border-collapse:collapse;width:100%;margin:12px 0}th,td{border:1px solid #aaa;padding:7px;text-align:left;white-space:normal;overflow-wrap:anywhere}th{width:24%;background:#eee}small{overflow-wrap:anywhere}@page{size:A4;margin:15mm}@media print{button{display:none}tr{break-inside:avoid}h2{break-after:avoid}}</style><button onclick="window.print()">印刷 / PDFとして保存</button><h1>運行指示書　第${v.number}版</h1><p>${demo ? 'デモ・正式指示ではない／架空データ' : '発行済み版の固定スナップショット'}　予定と実績は別記</p><table>${rows([['運行ID', trip.id], ['会社 / 営業所ID', `${trip.orgId} / ${trip.depotId}`], ['乗務員等', p.driverName + (p.crew ? '\n' + p.crew : '')], ['車両', p.vehicle], ['出庫予定', `${p.startPlace}\n${p.startAt} JST`], ['帰庫予定', `${p.endPlace}\n${p.endAt} JST（${p.returnProvisional ? '暫定' : '確定'}）`], ['最初 / 最後の勤務予定', `${p.dutyStart} → ${p.dutyEnd} JST`], ['運行経路', p.route], ['注意箇所', p.cautions], ['運転・業務交替地点', p.exchange], ['安全事項・休息計画', p.safety], ['次便未確定時の行動', p.fallback], ['次回連絡', p.nextContact + ' JST'], ['会社電話', p.officePhone], ['発行者 / 発行日時', `${v.issuer} / ${v.issuedAt}`], ['発行理由', v.reason], ['会社写し保存日時', v.companyCopy.savedAt]])}</table><h2>経過地・積卸・休憩・休息（予定・JST）</h2><table><tr><th>種別・地点</th><th>到着 / 開始</th><th>出発 / 終了</th><th>備考</th></tr>${p.stops.map(s => `<tr><td>${escape(kindLabels[s.kind])} / ${escape(s.place)}</td><td>${escape(s.arrive)}</td><td>${escape(s.depart)}</td><td>${escape(s.notes)}</td></tr>`).join('')}</table><h2>この版の直接対話記録</h2><table>${voices.length ? voices.map(r => rows([['実日時 / サーバー受信', `${r.actualAt} / ${r.receivedAt}`], ['担当者 / 相手 / 方法', `${r.manager} / ${r.recipient} / ${r.method === 'phone' ? '電話' : '音声通話'}`], ['指示内容', r.notes]])).join('') : rows([['状態', '未記録']])}</table><h2>この版のドライバー記録</h2><table>${drivers.length ? drivers.map(r => rows([['本人 / 実日時 / 受信', `${r.driver} / ${r.actualAt} / ${r.receivedAt}`], ['記録した内容', r.notes]])).join('') : rows([['状態', '未記録']])}</table><h2>端末保存通知</h2><table>${receipts.length ? receipts.map(r => rows([['端末 / 保存日時 / 受信', `${r.deviceId} / ${r.savedAt} / ${r.receivedAt}`]])).join('') : rows([['状態', '未通知']])}</table><h2>実績（予定とは別記・JST）</h2><table>${trip.actuals.map(a => rows([[kindLabels[a.kind] + ' / ' + a.place, `${a.startAt} → ${a.endAt}\n${a.notes}`]])).join('') || rows([['状態', '実績なし']])}</table><h2>版履歴</h2><table>${trip.versions.filter(x => x.number <= v.number).map(x => rows([[`第${x.number}版`, `${x.issuedAt} / ${x.issuer}\n${x.reason}`]])).join('')}</table><small>版ハッシュ（SHA-256）：${escape(v.hash)}<br>法定保存期限：${escape(trip.retainUntil ?? '運行終了後に確定')} / 社内方針（3年）：${escape(trip.policyRetainUntil ?? '未確定')}<br>この帳票は出力時点の双方記録を含む。固定版の計画内容は上書きしない。</small></html>`);
  win.document.close();
}

